import Head from 'next/head';
import Image from 'next/image';
import SearchBar from '../components/SearchBar';
import CoinsList from '../components/CoinsList';

export default function Home(props) {
  
  return (
    <div>
      <Head>
        <title>Crypto Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SearchBar />
      <CoinsList filterCoins={props.data} />
    </div>
  )
}



export const getServerSideProps = async ()=>{

  const res = await fetch('https://api.coingecko.com/api/v3/coins/markets?vs_currency=inr&order=market_cap_desc&per_page=10&page=1&sparkline=false');
  const data = await res.json();

  return{
    props:{
      data
    }
  }
};